version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env

    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
